{
 "title": "PFsense Firewall and IDS Dashboard 2025",
 "description": "A PFSense dashboard that displays Firewall and IDS (Suricata) events.  This dashboard uses Graylog for centralized log management while Opensearch is the data source backend used to perform queries/analytics against log data. ",
 "tags": [
  "Elasticsearch",
  "Firewall",
  "Log Analyzer",
  "PFsense",
  "Graylog"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "filterlog_ds", "label": "Filterlog Datasource", "query": "grafana-opensearch-datasource" },
   { "name": "IDS_Datasource", "label": "IDS Datasource", "query": "grafana-opensearch-datasource" },
   {
    "name": "iface",
    "label": "Interface",
    "query": "{\"find\": \"terms\", \"field\":\"interface\",\"timestamp\": {\n\"gte\" : \"now-$__Interval_ms\"\n}}"
   },
   {
    "name": "wan_ip",
    "label": "Destination IP",
    "query": "{\"find\": \"terms\", \"field\":\"dst_ip\",\"query\":\"interface:$iface\",\"timestamp\": {\n\"gte\" : \"now-$__Interval_ms\"\n}}"
   },
   {
    "name": "src_ip",
    "label": "Source IP",
    "query": "{\"find\": \"terms\", \"field\": \"src_ip\", \"query\": \"dst_ip:$wan_ip interface:$iface\", \"timestamp\": {\n\"gte\" : \"now-$__Interval_ms\"\n}}"
   },
   {
    "name": "dst_port",
    "label": "Destination Port",
    "query": "{\"find\": \"terms\", \"field\": \"dst_port\", \"query\": \"dst_ip:$wan_ip interface:$iface\", \"timestamp\": {\n\"gte\" : \"now-$__Interval_ms\"\n}}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Firewall Events on WAN=$iface",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:14",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:12", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND src_ip:$src_ip AND dst_ip:$wan_ip AND dst_port:$dst_port",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top IPs Blocked on WAN=$iface",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:120",
       "fake": true,
       "field": "src_ip",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:118", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "action:\"block\" AND interface:$iface AND src_ip:$src_ip AND dst_ip:$wan_ip AND dst_port:$dst_port",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "IDS Events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "source:Suricata",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Firewall Event Locations on $iface",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 3 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:974",
       "fake": true,
       "field": "src_ip_geo_country",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "asc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:975",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:972", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND src_ip:$src_ip AND dst_ip:$wan_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "IDS Event Locations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 3 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:5154",
       "fake": true,
       "field": "src_ip_geo_country",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:5155",
       "fake": true,
       "field": "timestamp",
       "id": "6",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5152",
       "field": "ip",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "src_ip:$src_ip AND dst_ip:$wan_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Firewall Pass/Fail Chart",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "action",
       "id": "2",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "2" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Firewall Blocked Destination Ports on $iface",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1775",
       "fake": true,
       "field": "dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1776",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1773", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Firewall Event Locations on $iface",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:974",
       "fake": true,
       "field": "src_ip_geo_country",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:972", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "interface:$iface AND src_ip:$src_ip AND dst_ip:$wan_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "IDS Event Locations",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:5154",
       "fake": true,
       "field": "src_ip_geo_country",
       "id": "7",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5152",
       "field": "ip",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "src_ip:$src_ip AND dst_ip:$wan_ip",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "IDS Destination Ports",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1933",
       "fake": true,
       "field": "dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1934",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:1931",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "dst_port:$dst_port",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Firewall Passed Destination Ports on $iface",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1775",
       "fake": true,
       "field": "dst_port",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1776",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1773", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "action:pass AND interface:em0",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Protocols On $iface",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1049",
       "fake": true,
       "field": "protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1050",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1047", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "IDS Protocols",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:5799",
       "fake": true,
       "field": "Protocol",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:5800",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5796",
       "field": "alert_description",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "IDS Alerts by Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:5799",
       "fake": true,
       "field": "Classification",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:5800",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:5796",
       "field": "alert_description",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Firewall Logs on $iface",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "IDS Alert Log",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}